# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FDwXWCxfW3UMzKxwx-X0vq3F_igA2Uay
"""

import csv

# Hardcoded stock prices
stock_prices = {
    "AAPL": 180,
    "TSLA": 250,
    "GOOGL": 140,
    "MSFT": 420,
    "AMZN": 175
}

portfolio = []
total_investment = 0

print("=" * 50)
print("        📈 STOCK PORTFOLIO TRACKER")
print("=" * 50)

print("\nAvailable Stocks:")

for stock, price in stock_prices.items():
    print(f"{stock}: ${price}")

print("\nEnter 'done' when you have finished adding stocks.\n")

while True:

    stock_name = input("Enter stock symbol: ").upper().strip()

    if stock_name == "DONE":
        break

    if stock_name not in stock_prices:
        print("❌ Stock not found. Please choose from the available stocks.")
        continue

    try:
        quantity = int(input(f"Enter quantity of {stock_name}: "))

        if quantity <= 0:
            print("❌ Quantity must be greater than 0.")
            continue

    except ValueError:
        print("❌ Please enter a valid number.")
        continue

    price = stock_prices[stock_name]
    investment = price * quantity

    portfolio.append({
        "Stock": stock_name,
        "Price": price,
        "Quantity": quantity,
        "Investment": investment
    })

    total_investment += investment

    print(f"✅ Added {quantity} shares of {stock_name}.")
    print(f"Investment: ${investment:,.2f}\n")


# Display portfolio
print("\n" + "=" * 50)
print("              YOUR PORTFOLIO")
print("=" * 50)

if not portfolio:
    print("No stocks added.")

else:
    print(f"{'Stock':<10}{'Price':<12}{'Quantity':<12}{'Investment'}")
    print("-" * 50)

    for item in portfolio:
        print(
            f"{item['Stock']:<10}"
            f"${item['Price']:<11}"
            f"{item['Quantity']:<12}"
            f"${item['Investment']:,.2f}"
        )

    print("-" * 50)
    print(f"Total Investment: ${total_investment:,.2f}")


# Save portfolio to CSV
if portfolio:

    with open("portfolio.csv", "w", newline="") as file:

        fieldnames = ["Stock", "Price", "Quantity", "Investment"]

        writer = csv.DictWriter(
            file,
            fieldnames=fieldnames
        )

        writer.writeheader()
        writer.writerows(portfolio)

    print("\n💾 Portfolio saved to portfolio.csv")

print("\nThank you for using Stock Portfolio Tracker! 📈")